version: '3.8'

# Docker Compose file for deploying from Docker Hub
# Usage: docker-compose -f docker-compose.hub.yml up -d

services:
  filesystem-api:
    # Replace 'yourusername' with your actual Docker Hub username
    image: chrisuthe/filesystem-api:latest
    container_name: filesystem-api-server
    ports:
      - "8000:8000"
    volumes:
      # Map your local directories to the container
      # Example: Map current directory to /data in container
      - ./data:/data
      # You can add more volume mappings as needed:
      # - /path/to/your/files:/data/files
      # - /path/to/documents:/data/documents
    environment:
      - FILESYSTEM_BASE_DIR=/data
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - filesystem-network

networks:
  filesystem-network:
    driver: bridge